[package]
name = "source-db"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
sqlx = { version = "0.8.0", features = ["postgres", "runtime-tokio", "tls-rustls"] }
types = { version = "0.1.0", path = "../types" }
